export const MOCK_USERS = [
  { id: '1', name: 'Alice DUPONT', avatar: 'user-1.jpg' },
  { id: '2', name: 'Bob MARTIN', avatar: 'user-2.jpg' },
  { id: '3', name: 'Charlie SMITH', avatar: 'user-3.jpg' },
  { id: '4', name: 'David JOHNSON', avatar: 'user-4.jpg' },
  { id: '5', name: 'Eve WILLIAMS', avatar: 'user-5.jpg' },
  { id: '6', name: 'Frank BROWN', avatar: 'user-6.jpg' },
  { id: '7', name: 'Grace DAVIS', avatar: 'user-7.jpg' },
  { id: '8', name: 'Hank MILLER', avatar: 'user-8.jpg' },
  { id: '9', name: 'Ivy WILSON', avatar: 'user-9.jpg' },
  { id: '10', name: 'Jack MOORE', avatar: 'user-10.jpg' },
  { id: '11', name: 'Karen TAYLOR', avatar: 'user-11.jpg' },
  { id: '12', name: 'Leo ANDERSON', avatar: 'user-12.jpg' }, 
  { id: '13', name: 'Mia THOMAS', avatar: 'user-13.jpg' },
  { id: '14', name: 'Nina JACKSON', avatar: 'user-14.jpg' },
  { id: '15', name: 'Oscar WHITE', avatar: 'user-15.jpg' },
]